apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gitlab-registry.collaborationlayer-traton.com/ats-project/ats-user-group/scania-thesis-students-ats/manish-master-thesis/fullstack-multiplayer:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-token-auth
